import { PropsWithChildren } from "react";

export const RecommendationAdviceCard = ({ children }: PropsWithChildren) => {
    return (
        <div>
            <h3 className="text-xl font-medium">
                Reusability advice from model
            </h3>
            <p className="text-sm text-slate-400">
                Result are generated by model using data from our database
            </p>

            <div className="space-y-2">{children}</div>
        </div>
    );
};
